{% set version = "2.8.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sjmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sjmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sjmisc/sjmisc_{{ version }}.tar.gz
  sha256: e2a12902a29824b680d36e9d6d7c332d6a1eb22681f199bf88182423c5920c9e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.8.0
    - r-haven >=1.1.2
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-sjlabelled >=1.0.17
  run:
    - r-base
    - r-dplyr >=0.8.0
    - r-haven >=1.1.2
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-sjlabelled >=1.0.17

test:
  commands:
    - $R -e "library('sjmisc')"           # [not win]
    - "\"%R%\" -e \"library('sjmisc')\""  # [win]

about:
  home: https://strengejacke.github.io/sjmisc
  license: GPL-3
  summary: Collection of miscellaneous utility functions, supporting data  transformation tasks like recoding, dichotomizing or grouping variables,  setting and replacing missing values. The data transformation functions  also support labelled data, and all integrate seamlessly into a  'tidyverse'-workflow.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ccwang002

# Package: sjmisc
# Type: Package
# Encoding: UTF-8
# Title: Data and Variable Transformation Functions
# Version: 2.7.9
# Date: 2019-03-16
# Authors@R: person("Daniel", "Ludecke", role = c("aut", "cre"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206"))
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# Description: Collection of miscellaneous utility functions, supporting data  transformation tasks like recoding, dichotomizing or grouping variables,  setting and replacing missing values. The data transformation functions  also support labelled data, and all integrate seamlessly into a  'tidyverse'-workflow.
# License: GPL-3
# Depends: R (>= 3.2), stats, utils
# Imports: dplyr (>= 0.8.0), haven (>= 1.1.2), magrittr, methods, purrr, rlang, sjlabelled (>= 1.0.17)
# Suggests: ggplot2, graphics, mice, sjPlot, sjstats, knitr, rmarkdown, rstudioapi, stringdist, testthat, tidyr
# URL: https://strengejacke.github.io/sjmisc
# BugReports: https://github.com/strengejacke/sjmisc/issues
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-03-16 21:46:28 UTC; Daniel
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>)
# Repository: CRAN
# Date/Publication: 2019-03-16 23:00:02 UTC
