# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "37OClYN5EIm79wc8rluMEq0xkl9Bzw1fdc5HaehqkFpCAVnVKBMzeojBXsMIAOCAT76LJj1SnTF42ENTgAC154U4qZpYRoSwvdgzde9lmoRK1cTYBS4QP5p9KFYRBR/pWRue0E94waBaw85FPS5pUeqvRFSxNWplLk1jwLrTaw51A95Q4eU14/Na5HajlviqjJg93qioPd+MlPTCjqjTGxDKuijT0yTy3hXCI8/KppCVKhdoOXL//N++96uHg/6jcu79IIZ5k8IuDgZ/rYS4ZjwfZM0mcy6E46xFhtK4i96JzD6s01KS++gAiXfCYVVQArR33i21Z97aHlH6J2sbZXHIRIl/VFAP5DaC04XddlcqO/yEX9uddUgc6+kpesAIrro9jk9NfpCpINOZM+QVPtKj2HBDUtDcGJujMK63zlHCacfXJ2XJhTSDcCoGltI50zeV1oGuaB4TsWCAUaVyqa6/A6iMnchRkGQRh/0lcqtP43CWro+Awg3B9vXQMxHBQ618Rje9IuVYpQV+guTihM0DEUupbaJJX0r67O3s98mvXlPc9V32cgIjYYCA6zM06EIHhkroMDzTMwF8AmPWXU7LXsjzGepJvKuqYLN9+3wGbk3pl76tZns//BOKAzbNtuTGQzCwnFPTgjhCskz8+cUg7Sj+gbg3lC8PybWGzOA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
