appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 37OClYN5EIm79wc8rluMEq0xkl9Bzw1fdc5HaehqkFpCAVnVKBMzeojBXsMIAOCAT76LJj1SnTF42ENTgAC154U4qZpYRoSwvdgzde9lmoRK1cTYBS4QP5p9KFYRBR/pWRue0E94waBaw85FPS5pUeqvRFSxNWplLk1jwLrTaw51A95Q4eU14/Na5HajlviqjJg93qioPd+MlPTCjqjTGxDKuijT0yTy3hXCI8/KppCVKhdoOXL//N++96uHg/6jcu79IIZ5k8IuDgZ/rYS4ZjwfZM0mcy6E46xFhtK4i96JzD6s01KS++gAiXfCYVVQArR33i21Z97aHlH6J2sbZXHIRIl/VFAP5DaC04XddlcqO/yEX9uddUgc6+kpesAIrro9jk9NfpCpINOZM+QVPtKj2HBDUtDcGJujMK63zlHCacfXJ2XJhTSDcCoGltI50zeV1oGuaB4TsWCAUaVyqa6/A6iMnchRkGQRh/0lcqtP43CWro+Awg3B9vXQMxHBQ618Rje9IuVYpQV+guTihM0DEUupbaJJX0r67O3s98mvXlPc9V32cgIjYYCA6zM06EIHhkroMDzTMwF8AmPWXU7LXsjzGepJvKuqYLN9+3wGbk3pl76tZns//BOKAzbNtuTGQzCwnFPTgjhCskz8+cUg7Sj+gbg3lC8PybWGzOA=
conda_forge_output_validation: false
