travis:
  secure:
    BINSTAR_TOKEN: c48APfhc/MKXXzcfGqSuxFje11t+XdhOw7kuVh6Mjmz8+8EoTv9vocnw+aeIfjxr/OVgGRaH9P+KxvXs8T4sF+CaSDRUYUk1uumW3hioOdjZyuWOE4KHVhDxlZoPHhiwYwJirctIpFZbIKy5JpKbaLgaS1VhBgitOPe//Bkwx/avZNHAZDx/JjvpXEr9j68re30Rnlze5kiN1s/JBkZpcirc/l5ERrXvW0HkvzP2jvA0WIy5iETywdH9LACMmi5NtBsrsCKSqhGyikGpmk+6cRHfgTdqSc9XZ4YM3Yg3TAdfp7Ec8zKP/mXt1FbBGQ5r/jOxfPMbrCzP4MjByfwdguVDeko1XP4/+hsJdL5DbXUsZRnGGJDKNqSsENV6Tv6JtLKeuWN+QYeEQjYuwuAN7Kf4VWlvK7gWWp4hp2Pf9ZepKxFv/Fz1JY4Fc/kQHSvF8PFxMrFyegL82vwfXCflcGiDhGBHX6C6OVNx5nzvsDYbEqOs5/CJxu9qFv7fzaSOY1HyWaa/G3A5uRzadOb6TghDY2eNw5f1nVcSTU9ZWlXu6He/B0rROhnPipXACa83owwbOm6ZY5T2jp8f6EQ7VUgmN63jzTHFIi6GpnA7f58wkHF9JJP8eaiaXR6kPauHwd3o9ruVEBsfiNBkHVvtD2b/Hu6FFAIq5rk3S7S5t+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
